// <auto-generated />
using System;
using HotsPatchNotes.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotsPatchNotes.Api.Migrations
{
    [DbContext(typeof(HotsDbContext))]
    [Migration("20260204182528_AddPatchSections")]
    partial class AddPatchSections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("HotsPatchNotes.Shared.Models.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbilityId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Cooldown")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hotkey")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTrait")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManaCost")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId", "AbilityId");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("HotsPatchNotes.Shared.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributeId")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpandedRole")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HyperlinkId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasePatch")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("HotsPatchNotes.Shared.Models.Patch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternateLink")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiveBuild")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialLink")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatchName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatchType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PtrBuild")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PtrDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PtrOfficialLink")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.HasIndex("LiveDate");

                    b.ToTable("Patches");
                });

            modelBuilder.Entity("HotsPatchNotes.Shared.Models.PatchSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("PatchId", "SectionType", "EntityName");

                    b.ToTable("PatchSections");
                });

            modelBuilder.Entity("HotsPatchNotes.Shared.Models.Talent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbilityId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AbilityLinksJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Cooldown")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TalentTreeId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TooltipId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId", "Level", "Sort");

                    b.ToTable("Talents");
                });

            modelBuilder.Entity("HotsPatchNotes.Shared.Models.Ability", b =>
                {
                    b.HasOne("HotsPatchNotes.Shared.Models.Hero", "Hero")
                        .WithMany("Abilities")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("HotsPatchNotes.Shared.Models.PatchSection", b =>
                {
                    b.HasOne("HotsPatchNotes.Shared.Models.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HotsPatchNotes.Shared.Models.Patch", "Patch")
                        .WithMany("Sections")
                        .HasForeignKey("PatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("Patch");
                });

            modelBuilder.Entity("HotsPatchNotes.Shared.Models.Talent", b =>
                {
                    b.HasOne("HotsPatchNotes.Shared.Models.Hero", "Hero")
                        .WithMany("Talents")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("HotsPatchNotes.Shared.Models.Hero", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Talents");
                });

            modelBuilder.Entity("HotsPatchNotes.Shared.Models.Patch", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
